### ISSUE TITLE
Compare django-machina and Misago, provide justification for picking one (or neither)

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#101]
This issue entails a comparison between Django-machina and Misago forum frameworks to ascertain the most suitable choice for our board games website's forum development. We aim to scrutinize both frameworks across various dimensions including ease of customization, user interface and experience, moderation features, scalability, and community support. We seek to identify the strengths, weaknesses, and challenges associated with each framework. The output will be a well-informed recommendation on selecting Django-machina, Misago, or neither ensuring our choice aligns with the project’s technical requirements, ease of implementation, and long-term sustainability.

**Comment by bburgess19** [comment]
## Progress
This issue can begin in earnest after completing both issues below:
- #100 
- #99

**Comment by bburgess19** [comment]
# Verdict
We've chosen django-machina over Misago.

## Rationale
The main reason we chose Django-machina was because Misago is designed to be a standalone product with minimal extensibility. We thought using this did not fit our use case and was against the spirit of the assignment. You can find more extended notes issue #100. Django-machina, however, is a more extensible product with a much higher potential to grow into our needs.

While other features such as ease-of-implementation and moderation features were of some importance in our decision, most important was whether or not we could build out our custom implementation with the library, and Misago was unfit for that. Additionally, django-machina has many other features including forum tree management, anonymous posting, and polls, and you can find more details in issue #99.

**Comment by bburgess19** [comment]
# Closing comment
We installed instances of both [django-machina](#145) and [misago](#146) in the sandbox directories, comparing their functionalities after writing full reports on them.

See the previous comment for more details on why we chose django-machina over misago.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! 
Thank you for linking the relevant issues and providing an in-depth rationale!
