### ISSUE TITLE
Tournament details view for spectator

### ISSUE THREAD

**Issue by rqueiroz20** [uchicago-cs/chigame#105]
This task requires us to create a details view for a spectator of a tournament. This shouldn't be too different from the details view of a player in a tournament, but we must ensure that a spectator can only join matches in a tournament to spectate a live game instead of playing in one. We could also add some high level information exclusive to spectators, but I'm not sure what those details would entail.

**Comment by MikeChen012345** [comment]
For the detail view, staff, non-admin users, and guests (not logged in) are all able to see the information related to the tournament. The fields displayed are ("name", "game", "start_date", "end_date", "max_players", "description", "rules", "draw_rules", "matches", "players", and "winners"). Note that we have merged issues #107 and #105  because currently, we recognize no need to create separate detail views for spectators and players, so only one detail view is created.

**Comment by MikeChen012345** [comment]
This issue is closed by PR #205 , we have implemented a basic create and detail view for the tournament model. During the process,
- Mike, Sam, and Joshua worked on the code. In particular, Mike and Sam mainly worked on the implementation of the views and HTML templates, while Joshua contributed a lot to the discussion of implementation details and mainly worked on giving feedback and suggestions from the List view that he was working on. 
- Rafael did the review. It was a pull request that took a long time, and he surely spent a lot of time reviewing the code. The effort is greatly appreciated!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
This issue provided much needed functionality for the tournaments feature. Updates and closing comment were very detailed as well.
