### ISSUE TITLE
Work with user profiles to see if user is in a tournament

### ISSUE THREAD

**Issue by rqueiroz20** [uchicago-cs/chigame#106]
Currently, there is no way to differentiate between a user that is participating in a tournament, a user that is spectating a tournament, and a user who is not currently in a tournament. We would like to work with the User Profile team to come up with a resolution to this problem. One idea I propose is to add an attribute that contains some variables that update when a user enters a tournament.

**Comment by rqueiroz20** [comment]
The current solution we came up with was that a user would receive a notification informing them that it is time to join their lobby for a match in the tournament once that tournament is full. This would be one of the many different notification types that would be sent out as specified in the Notifications class created by the Users team. We are not working with the other types of notifications for now, but if we need to, we can always revisit it. I'll close this issue for now, but if there are complications that arise as a result of this decision, we can modify our approach.

**Comment by elizabethli31** [comment]
Issue Score: Excellent.

Comments:
Good work reaching out and communicating with the user profiles team! I'd like to see some documentation next time if you decide to create a larger change. Because this issue only focused on communication and didn't result in any changes yet, I'm going to make it a minor issue.
