### ISSUE TITLE
Details view for player

### ISSUE THREAD

**Issue by rqueiroz20** [uchicago-cs/chigame#107]
This task involves creating a details view for a player in a tournament. They should be able to see the tournament type, the rules of the tournament, a list of players in the tournament, and some other details that have not been fully established yet.

**Comment by MikeChen012345** [comment]
For the detail view, staff, non-admin users, and guests (not logged in) are all able to see the information related to the tournament. The fields displayed are ("name", "game", "start_date", "end_date", "max_players", "description", "rules", "draw_rules", "matches", "players", and "winners"). Note that we have merged issues #107 and #105  because currently, we recognize no need to create separate detail views for spectators and players, so only one detail view is created.

**Comment by MuyanXie** [comment]
Closing Statement:

@rqueiroz20 worked on creating a scratch for what the classes and attributes should look like in the details view
@MikeChen012345 and @MuyanXie worked on implementing the idea in code

**Comment by elizabethli31** [comment]
Issue Score: Unsatisfactory

Comments:
Marking this as unsatisfactory for grading purposes because this issue was merged with #105
