### ISSUE TITLE
Implement the "join lobby" feature

### ISSUE THREAD

**Issue by xylucien** [uchicago-cs/chigame#118]
Planning on implementing the join lobby button on the lobby detail page. If the user is not logged in or already joined the lobby, hitting this button should raise a 404 error.

**Comment by xylucien** [comment]
Update: The join button basic functionality is done. Waiting to sync progress with Moses on his leave button implementation.

**Comment by xylucien** [comment]
Update: when testing around I find it necessary to create some sort of fixture to expedite the process. Created a new issue for this.

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and closed
Task is successfully finished with an error message instead of a 404 error

Lucien: designed the logistics and helped implement the button
Moses: did most of the implementation
Chloe: helped identify ways to beautify the page, such as displaying an alert messaage

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Join lobby was a very fundamental element to provide functionality for lobbies. You guys did a great job with implementing this issue and providing updates as well.
