### ISSUE TITLE
write API tests to test API endpoints /api/games/ and /api/games/<pk>

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#122]
Writing tests in chigame/api/tests.py. Specifically, testing the functionality of the `api/games/` and `/api/games/<int:pk>` endpoints. Ensuring that the List Games View supports both GET and POST requests. Also ensuring that the Detail Games View supports PATCH and DELETE requests.

Will be completed when the tests run and pass.

**Comment by abrahmasandra** [comment]
Closing statement: Wrote pytests in `chigame/api/tests.py` to test the implementation of the Chigame API, specifically checking the implementation of the Games list and detail view endpoints.

@abrahmasandra: wrote the code for the tests

**Comment by majorsylvie** [comment]
Issue Score: Satisfactory

Comments:
Nice work! 
Happy to see you using the inline code formatting to improve the readability of your comments. 

This issue does not have any closing comments, which is significant.
Especially because you actually did write a lot of tests, no updates on your progress or mentions of any problems you had in implementation leaves me wondering what happened between start and end.

In the future, even for issues that are straighforward, please add updates comments describing your process. 
This would include any decisions you made, eg: what kind of tests you chose to write, or if you're unsure how to test certain functionality.

Overall, this is still good work, very good opening and closing statements, and good job linking this issue to the related PR.

Keep going!
