### ISSUE TITLE
Edit `views.py` for tournament

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#137]
**Description:**

To better support our tournament features in the `src/chigame/games/views.py`:

- Introduce a new class, `TournamentListView` (or something similar) to handle tournament-specific listings.
- Implement queries within this class to retrieve relevant tournament matchups.
- Ensure the template context reflects the new structure for tournament matchups.

**Comment by jb-01** [comment]
Closed as PR #138 was successfully merged.

**Comment by MuyanXie** [comment]
Closing Statement:

@jb-01 worked on creating tournamentListView classes to display the tournaments better
@MikeChen012345 and @MuyanXie worked on researching the best way to approach this feature

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Good work implementing this issue. I would have liked to seen updates on this issue since it had a substantial amount of work involved. Also, the title is a bit generic and confusing as it doesn't actually pertain to the description of this issue. FYI you guys will only get 70% of the points for this issue since 4 people are assigned.
