### ISSUE TITLE
Limitations for users creating tournaments

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#173]
In this issue, we will determine what is the limitations on the staff/non-staff users to create tournaments and implement any changes. By doing so, we wish to allow specific groups of users to create tournaments that are available to designated players using the create tournament view in the games/views.py method, and allow tournament creators to edit their own tournaments

**Comment by MuyanXie** [comment]
Upon dicussion, we determined a preliminary set of rules for creating tournaments for users:

Staff users:
- Allowed to create Tournaments
- Allowed to specify who are the tournaments open to for any tournaments
- Allowed to delete/disable any Tournaments
- Allowed to edit any Tournaments
- Have access to details of any Tournaments

Non-staff users:
- Allowed to use tokens to create Tournaments (contact user's team to get this done, which is also considered a scope within this issue)
- Allow to have full edit control over their own tournaments
- Allow to join tournaments that they have access to
- Allowed to delete/disable the tournament they created
- Cannot access the tournaments that is not opened to them

@MikeChen012345 Please let me know if you have questions or concerns about this scheme! Once we get this done, we can approach the user's team about the token stuff

TODO:
- Add this to wiki
- contact user team for this

**Comment by MikeChen012345** [comment]
Great jobs! I think we can add a statement that 
- staff users are allowed to delete/disable any tournaments, but they should NEVER do this unless in an emergency (such as when a tournament is created with bugs that can tear down the website altogether). 
- Also, non-staff users should not be allowed to delete/disable the tournament they created but should contact staff users to do so because the deletion of a tournament can lead to a bunch of different events that need to be handled. 
- staff users may remove matches/players from a tournament in an emergency (such as if they detect that a player is cheating), but generally, they should NEVER add matches/players because it is unfair to other players. 
- Non-staff users would not be able to remove/add matches/players to a tournament.

**Comment by MuyanXie** [comment]
Awesome I agree! Would you like to finalize this onto Wiki @MikeChen012345 ?

**Comment by MuyanXie** [comment]
Found the [wiki page](https://github.com/uchicago-cs/chigame/wiki/Tournaments-~-Limitations-for-Users-Creating-Tournaments)! Thanks @MikeChen012345 ! I'll mark this as complete and close it

**Comment by MuyanXie** [comment]
I'm closing this issue. @elizabethli31 Please review this issue~

**Comment by MikeChen012345** [comment]
A follow-up on this issue: currently, admin users and non-admin users cannot remove/add matches/players from/to a tournament due to the limitation of the default update view provided by Django. If the feature needs to be implemented, a new approach should be explored (e.g., by adding a remove players/matches page).

**Comment by MuyanXie** [comment]
Closing Statement:
@MikeChen012345 Helped identified limitations for non admin users to create tournaments
@MuyanXie Wrote the documentation and coordinate with other team to move forward

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great work providing consistent updates on this issue! Wiki page is also a nice addition to explain your reasonings for these limitations. PR not closed yet, but good work detailing the functionalities you want!
