### ISSUE TITLE
Storing Match Outcomes

### ISSUE THREAD

**Issue by ambr-lise** [uchicago-cs/chigame#200]
Ideally, we would have some generic/modular way to create a match record, as well as the corresponding user record(s). But I think we are just going to store them relative to our particular placeholder game for the time being: namely, it will be part of the game functionality that the relevant records will be created as part of the game functionality.

**Comment by nugerhard** [comment]
Integrated as part of pr #345

Closing Comment: At the moment, a match record is created when the first user goes to join a game from the lobby. The code pulls in the game data from the lobby and stores it in the match field (which is somewhat modular). However, the player records (with corresponding wins and losses) are only created once the user finishes playing the game: in the future design of this functionality, some more general construct should be used. The self-contained game should return json data or something like that, which is then converted into player records: the "game" in itself should not be writing to the db.

Nat and Annika: updated the views.py functions for "placeholder-game" and "flip-result" so that a player record is stored whenever a user plays a game, with this record reflecting the outcome of the coin toss. Added conditionals so that when the user finishes playing, if all users in the lobby have played, the lobby record reflects that the match is finished.

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Nice work implementing this issue! Taking off points as there are no status updates or label indicating your team.
