### ISSUE TITLE
Research the best ways and alternatives for implementing the live chat feature

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#202]
This feature may not be specifically for tournaments. The live chat can be a pop-up window that shows up on the page to allow users (may be different for players and spectators, but the differences might be implemented later). We may use some plug-ins or 3rd-party libraries to implement the live chat. This issue can be split into multiple smaller issues and pull requests.

**Comment by MuyanXie** [comment]
@elizabethli31 Mike and I have researched a little bit and came up with two solutions to provide a live chat feature. This comment will server as a documentation of our research into this issue and provide references.

## Option 1: Use SocketIO
SocketIO is a JavaScript library that enables real-time bidirectional communication between the frontend and backend. It is commonly used to implement live chat and notifications in web applications.

Some advantages of using SocketIO:

- Real-time communication without constant polling from the frontend
- Efficient data transfer with binary encoding
- Auto-reconnect on lost connections
- Works well across different platforms and browsers
- To implement with SocketIO:

Install SocketIO library on both frontend and backend:

- Setup SocketIO connection on the frontend from client to server
- Listen and emit events on the backend to send/receive messages
- Save chat messages to database
- Emit chat messages to connected clients in real-time

Some considerations:

- More complex setup than a basic API
- Need to scale WebSocket connections on the backend
- Payload size per message should be small

References: Django [GEvent-SocketIO](https://www.codysoyland.com/blog/evented-django-part-one-socketio-and-gevent/), Backend and Frontend Server [Real Time Communication](https://dev.to/jszutkowski/real-time-two-way-communication-between-frontend-and-backend-using-sockets-5ghc)

## Option 2: Use a Combination of Regular Frontend Query and Robust Backend CRUD Suites

Rather than real-time communication, fetch new messages from the backend regularly (e.g. every 1 seconds).

Some advantages:

- Simpler to implement than WebSockets
- Built on common REST API patterns
- Leverages robust backend CRUD & storage

To implement:

- Create frontend component to fetch messages from API endpoint
- Backend API retrieves new messages from database
- Frontend polls API to check for message updates
- Shows new messages in real-time-like fashion

Some considerations:

- Added latency compared to WebSockets
- Potential overfetching/underfetching of updates
- More API requests required

In general, SocketIO offers a more complex way to implement chat, while regular frontend query is more communication heavy but can be straightforward.

That being said, at this moment, we actually prefer the second option as it is easier to implement, but we also recognize the disadvantages it have. Please let us know what you think so that we can fully understand the team's requirements!

**Comment by MuyanXie** [comment]
Upon confirmation from @elizabethli31 , we are going to pursue the second option to Use a "Combination of Regular Frontend Query and Robust Backend CRUD Suites"

We will then implement the CRUD for Chat, CRUD for Message, and reasonable frontend features to finally achieve this live chat box. The details about this implementation, as for now, is designed to follow the pattern described above.

**Comment by MuyanXie** [comment]
Wiki [here](https://github.com/uchicago-cs/chigame/wiki/Tournaments-~-Implementing-the-Live-Chat-in-Tournaments) @MikeChen012345  Please let me know what you think about this.

**Comment by MikeChen012345** [comment]
Looks good to me! We can use this document to start our work!

**Comment by MuyanXie** [comment]
Awesome! I'll close this issue for now. Subsequently, please refer to issue #225 #226 #227 #228 #229 for implementation and details!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Very in-depth updates and clear Wiki page as well. Missing a closing statement, so make sure you include that for the other issues related to this one!
