### ISSUE TITLE
Implement display of chat box and chat content at the frontend

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#225]
In this issue, we will create a very basic frontend display module for the chat content.

## TODO

1. Implement a tournament match chat display page
2. implement a js file that contains the logic for displaying, fetching, and auto-fetching/display changes
3. implement user-friendly features for users to use this as a chat box

## metrics

1. the user can now navigate to the page
2. the user can have auto-updates 
3. the user can scroll down the page
4. the latest message will always be at the bottom of the chat box

**Comment by MuyanXie** [comment]
Reference Link for our design of the frontend-backend communication pattern:

https://github.com/uchicago-cs/chigame/wiki/Tournaments-~-Implementing-the-Live-Chat-in-Tournaments

**Comment by MuyanXie** [comment]
Closing statement:
@MuyanXie  identified the TODOs and metrics of this issue and coded the features in a corresponding PR.
@MikeChen012345  and @jb-01 gave very detail context of this issue and helped finalize the features of the chat box. They also engaged in discussion about the best way to implement the chat box in js and HTML files

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great work on this issue/PR! The mock looks really good and good documentation on why you chose frontend/backend interaction instead of a more complicated API. Only comment is that next time for an issue that requires implementation, you can just link the PR with it, and it will be closed after the PR closed. Since the PR hasn't been closed yet, this issue technically shouldn't either. Regardless, good job!
