### ISSUE TITLE
Update Game Factory to have a unique category field for creation

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chigame#243]
Currently, the game factory can create models that have duplicates of certain fields such as categories.
However, there are uniqueness constraints on the game model. Which can cause integration tests to fail non-deterministically as sometimes random generation will not produce the same categories, but sometimes it will.

This task would involve updating the game factory to use some kind of method to generate attributes like categories in a way that maintains uniqueness. For example, and autoincrementing name like `Category 1` then `Category 2` etc...

**Comment by frowenz** [comment]
Pull request, https://github.com/uchicago-cs/chigame/pull/236, has a fixture with all the categories and mechanics which could possibly be of use

**Comment by cuyakonwu** [comment]
Just created Pull Request #299 to address this issue

**Comment by abrahmasandra** [comment]
Closing Comment: 

This issue modified the `CategoryFactory` so that there is no chance of creating multiple `CategoryFactory` models with the same name during testing. Before, there were non-uniquely named `Category` objects being created, causing errors in testing. Now, Category factories are named using an `auto-incrementing` integer (Category 1, Category 2, etc.) so there is no chance of them having the same name. This change was implemented using the `Sequence` function within the `factory` module.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job! Thank you for fixing this bug and moving within the agile method.
@abrahmasandra this closing comment is particularly good! thank you for being very descriptive and fully describing the problem.
