### ISSUE TITLE
Add filtering to game grid page

### ISSUE THREAD

**Issue by willcravitz** [uchicago-cs/chigame#249]
The api team has developed a filter for games using `django-filter` and is currently updating it in issue #230 to account for all new bgg attributes. We'll take the filter that they develop and implement it on our game grid view so that games can be filtered by different attributes.

**Comment by willcravitz** [comment]
Opening up a new branch `game-management/filter` to address this issue. 

Messaged the api team to ask whether we can move `api/filters.py` and `api/tests/factories.py` into our `games/` directory.

**Comment by willcravitz** [comment]
I have an initial version of filter working but it doesn't look good. Looking into using this guide https://simpleisbetterthancomplex.com/tutorial/2016/11/28/how-to-filter-querysets-dynamically.html for styling or finding some Django bootstrap form package.

**Comment by willcravitz** [comment]
Another issue that needs to be worked out is getting filtering and pagination to work together. Right now navigating to a new page of games causes the filter to be removed.

**Comment by frowenz** [comment]
I have updated filtering logic to use querysets instead of the GameFilter class. This change was driven by the need for more granular control over queries, especially when combining sorting, filtering, and search. The code has been rewritten such that sorting and filtering plays nicely with pagination and with search. I have added sorting only for the following criteria and filtering only for number of players. Some good next steps would be to add more options. 

<img width="470" alt="Screenshot 2023-11-29 at 5 45 05 PM" src="https://github.com/uchicago-cs/chigame/assets/69015620/4838a070-6d6c-4542-b173-e27f975ebc5e">


Note: SORTING refers to how results are ordered (e.g., by year published) and FILTERING refers to what how to include games (e.g., 4 player game)

**Comment by willcravitz** [comment]
Used this resource (https://blog.ovalerio.net/archives/1512) to create a new custom template tag. This allows links to new pagination page urls while keeping all existing url parameters, allowing pagination on the search results page.

I also make some very minor updates to the game detail page. I didn't want to push these through in a whole separate issue and PR.

**Comment by willcravitz** [comment]
Closing comments: This issue resulted in the following
1) On the game browse page (and search results page), users are able to filter by number of players or sort by name, playtime, or year published.
2) Filtered/sorted pages and the search results page support pagination by introducing a new custom template tag `updated_params`. This template tag returns the current url updated by provided parameters.

Developer contributions:
@willcravitz tried to make the initial filter with `django-filter` and created the template tag so that search results could be paginated
@frowenz rewrote filtering/sorting and provided nicely styled forms for filtering/sorting in the template

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Awesome feature y'all!
@willcravitz appreciate you directly linking to all the sources you used as reference for implmentation!
Appreciate that the summary explicitly mentions the work done by the API team instead of only saying "we want filtering". Adds further context and communicates what tool y'all will be using for this issue!

@frowenz thank you for your design work! Together this is a great feature with wonderfully done issue work. 

Keep moving forward!
