### ISSUE TITLE
Create Voting Functionality On Posts With Cumulative Counter

### ISSUE THREAD

**Issue by giomhern** [uchicago-cs/chigame#253]
# Goal
Implement a voting feature for posts in our application, allowing users to express appreciation or disapproval for content. 

## Notes
Each post should display a cumulative count of likes and dislikes it has received. The resulting displayed number will be the sum total of the likes and dislikes.

**Comment by bburgess19** [comment]
# Implementation Details

## Unique `Vote` model
I believe we should use an entirely different model `Vote` to model an individual like/dislike. This prevents overriding any of the django-machina models which is involved and may involve lots of code duplication.

## One `Vote` per post
We'd want to make sure each user votes only once per post, and that is only possible if there is a unique constraint on users and posts, giving more credence to having our own model.

Here is an ERD (with unnecessary attributes removed) to demonstrate my idea:

<img width="669" alt="image" src="https://github.com/uchicago-cs/chigame/assets/55334507/7c7f7830-6a98-4c09-b71a-23dc4644e2b2">

**Comment by bburgess19** [comment]
# Closing comment
In #341, I added a like button which appears on posts.

## Implementation Details
### Overriding `forum_conversation`
In order to implement the `Post` as described in the ERD, we needed to add a through table `Vote`. This meant **extending django-machina's implementation** of `Post` to add a `ratings` field which keeps track of all of the votes for that post.

There were several notable changes necessary to extend django-machina's forum_conversation app:
- Changing our `forum` app to `base`
  - This meant nesting both `forum_conversation` and `base` inside of a `forums` directory, effectively encapsulating all of our forum logic
- Inheriting any classes django-machina classes created by `forum_conversation`. In our case, `Post`
- Removing `machina.apps.forum_conversation` from our `THIRD_PARTY_APPS`

Each `Vote` instance is uniquely identified by `Post` and `User` primary keys. This will be useful if we ever want to add extended functionality with likes, e.g. keeping track of liked user posts on their profile page.

[Here](https://django-machina.readthedocs.io/en/latest/customization/overriding_applications.html) is more documentation for overriding django-machina app implementations.

### `topic_detail.html` and Javascript
The only way I was able to access variables provided by the template using django template syntax in Javascript was to embed the Javascript code in a `<script>` tag at the bottom of `topic_detail.html`. This doesn't feel in the spirit of modular coding, so **this may be a source of improvement.**

### Handling Voting Logic
When a user likes/dislikes, a POST request is sent with their vote. `TopicView` in our `forum_conversation` extends the class in django-machina's implementation to add functionality for POST requests to a topic URL. We validate the data in topic view and process the request if so.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
