### ISSUE TITLE
Fix the way that game descriptions are displayed

### ISSUE THREAD

**Issue by willcravitz** [uchicago-cs/chigame#258]
As of right now, game descriptions make the cards on the game browse page way too long. We need to display a shortened version of the description. There are also several XML special characters like `&#10;` that we need to interpret correctly.

![Image](https://github.com/uchicago-cs/chigame/assets/93291811/5185e5db-4784-4b92-897f-5b271963da22)

**Comment by willcravitz** [comment]
One way we could shorten the description is with the built in Django `truncatewords` and `truncatechars` template tags, described [here](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/?from=olddocs#truncatechars).

**Comment by willcravitz** [comment]
Created branch `game-management/descriptions` to address this issue.

**Comment by willcravitz** [comment]
I think I found a fix for the special XML characters that show up in descriptions. It requires manipulating the XML output from the BGG API call before we save them into the fixtures or use them for autofill. It will look something like this:
```py
import xml.etree.ElementTree as ET
import xml.sax.saxutils

game_url = f"https://www.boardgamegeek.com/xmlapi2/thing?id={id}&stats=1"
game_response = requests.get(game_url)
text = xml.sax.saxutils.unescape(game_response.text)
game = ET.fromstring(text)
```

I've opened a new issue #283 to address this.

**Comment by willcravitz** [comment]
Because BGG descriptions are really long, on the game detail page I changed them from being a header beneath the title to text in the information section. I think it's still worth having a short description or tagline to go along with games, which BGG does have...
<img width="400" alt="image" src="https://github.com/uchicago-cs/chigame/assets/93291811/e023e21f-a577-4002-901a-f48ff34de878">
... for CATAN it's "Collect and trade resources to build up the island of Catan in this modern classic." Unfortunately this short description is not supported in the API. We could look into webscraping to get them.

With that I'm going to open a PR to merge these changes in.

**Comment by majorsylvie** [comment]
> One way we could shorten the description is with the built in Django `truncatewords` and `truncatechars` template tags, described [here](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/?from=olddocs#truncatechars).

@willcravitz 

FYI it is better for readability and accessibility to not add a hyperlink to one work. 

Since there are folks who for whatever reason might not be able to distinguish the link color from the background / other characters. As well as the link being quite small (since here is only 4 letters).

Best practice for maximizing readability and making it easier to click and interact with is to add "here: https://docs.djangoproject.com/en/4.2/ref/templates/builtins/?from=olddocs#truncatechars "

I've had issues in my own job at CSIL where my boss has not been able to read someone documentation because they kept using these markdown hyperlinks. 

Happy to explain more if you'd like!

**Comment by majorsylvie** [comment]
> One way we could shorten the description is with the built in Django `truncatewords` and `truncatechars` template tags, described [here](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/?from=olddocs#truncatechars).

@willcravitz 

FYI it is better for readability and accessibility to not add a hyperlink to one work. 

Since there are folks who for whatever reason might not be able to distinguish the link color from the background / other characters. As well as the link being quite small (since here is only 4 letters).

Best practice for maximizing readability and making it easier to click and interact with is to add "here: https://docs.djangoproject.com/en/4.2/ref/templates/builtins/?from=olddocs#truncatechars "

I've had issues in my own job at CSIL where my boss has not been able to read someone documentation because they kept using these markdown hyperlinks. 

Happy to explain more if you'd like!

**Comment by willcravitz** [comment]
Closing comments: This issue started with the observations that descriptions from BGG are far longer than our UI is built to support, and they have special XML characters. I opened issue #283 to address the XML characters. The outcome of this issue was to truncate descriptions on cards to 20 words and decrease the size of the descriptions on game detail pages. I've suggested adding a "short description" field from BGG that can fill the place of where the old description used to be.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Phenomenal work @willcravitz ! Your updates have been fantastic all quarter and this one is issue is no different.
Appreciate your use of images along with good description to capture the problem.

Thank you for you work!
