### ISSUE TITLE
(user profiles) Add friend invitations endpoints

### ISSUE THREAD

**Issue by 24raniwalar** [uchicago-cs/chigame#29]
We need endpoints to allow users to send and cancel friend requests. Profile pages need to reflect the status of a friend request. That is, it should display an Add Friend button if users are not friends and there is no friend invitation already and Remove Friend button if they are already friends and Cancel Friend Request if users are not friends but there is friend invitation already.

**Comment by 24raniwalar** [comment]
Friend feature should allow users to send invites to users they have the username / email

**Comment by omarelkashef** [comment]
@24raniwalar and I decided that we also need to add a search bar (#68) to allow user to search for friends to add

**Comment by omarelkashef** [comment]
This issue builds on #28 so that add friend button in profile page sends a friend request.

**Comment by omarelkashef** [comment]
We have added a Remove Friend button to the profile page but the logic for the button can be implemented in a different issue that handles responding to friend invitations(accepting, denying, removing)

**Comment by omarelkashef** [comment]
Per a conversation with @24raniwalar , @borjasotomayor , we decided that accepting a friend invitation on the admin site will not add a friend to a UserProfile for now. Currently, it is the admin responsibility to manually add friends if the process needs to be done through the admin site.

**Comment by omarelkashef** [comment]
Closing statement: We added endpoints for sending and canceling friend request using user id and modified the profile page logic to reflect the status of this request and also include button that post to the new endpoints. This issue brought our attention to the need of creating a searching feature #68. We also decided that accepting a FriendInvitation through admin site is the admin's responsibility since that change will not be reflected in the app in this issue.

@omarelkashef worked on creating new friending endpoints 
@24raniwalar worked on making the profile page buttons use of the new endpoints

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work! Super clear updates, but your summary description is a little too terse. Glad you are adding a searching feature this sprint instead of needing to manually go to each users profile through url.
