### ISSUE TITLE
Add Nested Endpoints to GET information about Game model

### ISSUE THREAD

**Issue by abrahmasandra** [uchicago-cs/chigame#294]
With the updates to the `Game` model, there are now two new attributes `Mechanics` and `Categories`, that are represented as many to many relationships. We would like an endpoint to easily GET the mechanics and categories of a given game. This is very similar to the code needed to get the friends of a given user in previous issue #54. We will create two endpoints `/api/games/<game_id>/mechanics` and `/api/games/<game_id>/categories` that get the mechanics and categories of a given game respectively

We will know this issue is completed when the two endpoints described above are completed.

**Comment by abrahmasandra** [comment]
Closing Comment:

Created 2 endpoints that support `GET` requests: `/api/games/<game_id>/categories` and `/api/games/<game_id>/mechanics` to get the categories and mechanics respectively of the game specified by the `game_id`.

**Comment by majorsylvie** [comment]
Issue Score: Satisfactory

Comments:
Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.

Especially given that you also chose to modularize the URLS in this issue!
