### ISSUE TITLE
Fix inconsistent nav bar offset on forums page

### ISSUE THREAD

**Issue by joshuamonroe** [uchicago-cs/chigame#324]
While integrating the nav bar into the forums page, a bug was discovered that causes the nav bar to have an inconsistent offset between the forums page and the rest of the website.

https://github.com/uchicago-cs/chigame/assets/86740254/bd80e8fc-261c-4a56-9978-fbd0196798fe

_Originally posted by @majorsylvie in https://github.com/uchicago-cs/chigame/pull/272#pullrequestreview-1756620033_

**Comment by Benjoman12** [comment]
The issue relates to line 17 in board_base.html. Opening up a branch to resolve it.

**Comment by Benjoman12** [comment]
After reading through the 10,000 lines of CSS, static/css/machina.board_theme.vendor.min.css, that is included in the aforementioned line 17 in board_base.html it is clear that there are two classes in the CSS causing the offset: navbar and container-fluid.

**Comment by Benjoman12** [comment]
A separate css file has been made and properly placed to address the navbar offset issue and I have submitted a pull request to merge it into dev.

* https://github.com/uchicago-cs/chigame/pull/350

**Comment by Benjoman12** [comment]
Aside from having to read through the 10,000 lines of bootstrap this issue was decently straightforward to deal with. Our method of implementation allows for future coders to expand on the customization of django-machina's default styling.   Closed after successfully merging and closing PR https://github.com/uchicago-cs/chigame/pull/350. Thanks to @joshuamonroe for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
