### ISSUE TITLE
Add Junk box for deleted Notifications

### ISSUE THREAD

**Issue by AndrewM131** [uchicago-cs/chigame#339]
Currently you can delete notifications on the admin page. They're marked as deleted but they're not actually removed (visible attribute is set to false). Add a filtering feature where the visibility is set to false.

**Comment by henrietta-k** [comment]
Update: had a group meeting on Nov 30 to discuss how to implement this. Will add a filtering option to allow the user to only view removed (visible attribute set to false) notifications

**Comment by henrietta-k** [comment]
Update Nov 30: a button was added to the user's inbox called "Show Deleted Notifications" so that when the user clicks on it, it'll take them to a new page with all their deleted notifications. All the notifications on this page can be moved back to the original inbox if the user clicks on "Move to Inbox," and they will all be marked as unread.

**Comment by henrietta-k** [comment]
Closing statement:
The issue has been addressed. In the user's inbox, they can now choose to see all their deleted notifications and move it back into their main inbox (marked as unread) if they want. All the assignees worked together to write the code but I was in charge of making the GitHub PR.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Cool addition to the inbox functionality!
