### ISSUE TITLE
(tournaments) user stories for tournament in progress

### ISSUE THREAD

**Issue by rqueiroz20** [uchicago-cs/chigame#34]
This issue should focus on describing the user experience while actively participating in a tournament. Specifically, we should focus on a double elimination style bracket, but more tournament types, such as single elimination, can be discussed as well. Examples of what could be included in these user stories includes what happens when a user wins or loses a match, how the matches are determined, and some sort of live chat depending on the game itself.

**Comment by MuyanXie** [comment]
As a participant, I want to receive a notification when my match in the tournament is about to begin, so that I can be prepared and join promptly.

As a participant, I want clear instructions on how the matches are determined, including who my opponent is and which side I'll be playing (e.g., left or right side of the bracket).

As a participant, I want the system to update the bracket in real-time after each match, so that I can track my progress and see who my potential future opponents are.

As a participant, I want to be notified immediately after the match is over, indicating whether I won or lost, and what the next steps are in the tournament.

As a participant, I want the option to review match statistics, such as scores, time played, and any other relevant metrics, after the match concludes.

As a participant, I want the ability to engage in live chat with my opponent and spectators during the match, fostering a sense of community and sportsmanship.

As a participant, I want to see a clear visual representation of the tournament bracket, showing both my progress and the overall state of the tournament.

As a participant, I want to understand the rules and format of the tournament (e.g., double elimination, single elimination) before it begins, ensuring a fair and competitive environment.

As a participant, I want to have the option to spectate other ongoing matches within the tournament, providing an opportunity to learn from other players and observe different strategies.

As a participant, I want to receive a congratulatory message or acknowledgment when I advance to the next round, celebrating my progress in the tournament.

As a participant, I want the option to communicate with tournament organizers or administrators in case of disputes, technical issues, or other concerns during the tournament.

As a participant, I want the system to provide clear guidelines on tiebreakers or sudden death scenarios, ensuring a fair resolution in case of a match draw.

**Comment by rqueiroz20** [comment]
@MuyanXie I made some modifications to your user stories if you want to view them again before I close the issue. Can you review them and let me know if they look good to you?

**Comment by rqueiroz20** [comment]
@MuyanXie and I discussed on Slack and we agree with the current user stories for a tournament in progress. I'm closing the issue for now, but if there's additional things we didn't think of, we can always come back to the user stories.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great job! Super in-depth, especially with the addition of wifi disconnection. I'm counting Sam's comment as a closing statement. But next time, leave a thorough closing statement and do not use the comments as a space to discuss.
