### ISSUE TITLE
(tournaments) user stories for displaying tournaments

### ISSUE THREAD

**Issue by jb-01** [uchicago-cs/chigame#35]
This issue should resolve the creation of multiple, descriptive, user stories which depict how tournaments get displayed from the perspective of the _user_.

**Key Points:**

1. **Purpose:** To establish clear and concise user stories that detail how users will interact with the tournament display feature.
2. **Benefit:** User stories will help developers understand the desired functionality and user experience from the perspective of the end-users.
3. **Scope:** This will likely cover various scenarios such as viewing an individual tournament, browsing a list of tournaments, interacting with tournament details, etc.

**Possible Related Areas to Consider:**

- Filters or search functionalities for finding specific tournaments.
- Displaying relevant information like tournament dates, participants, and status.
- User interactions like registering for a tournament, viewing results, or sharing the tournament details.

**Comment by jb-01** [comment]
@rqueiroz20

Do you want to add a "General" section to your user stories to outline features which apply to both the spectator and player?

Here's a potential template:

# User Stories for Displaying Tournaments

**Spectator Stories**:
1. As a spectator, I want to view the schedule and progress of tournaments, so I can know when matches are taking place and follow the results in real-time.
   
2. As a spectator, I want to see the leaderboard and player statistics, so I can track players' performances and make predictions.
   
3. As a spectator, I want to watch live streams and view match highlights, so I can engage with the action and catch up on any missed content.
   
4. As a spectator, I want to participate in tournament chat rooms, so I can discuss matches and interact with other viewers.

**Player Stories**:
1. As a player, I want to view the tournament bracket and schedule, so I can see my opponents and match timings.
   
2. As a player, I want to track my progress in the tournament, so I can see how far I've advanced and what's next.
   
3. As a player, I want to access the tournament rules, prize pool, and relevant social feeds, so I'm informed and motivated.

**General Stories**:
1. As a user, I want to use filters or search functionalities, so I can easily find specific tournaments.
   
2. As a user, I want to see relevant tournament information like dates, participants, and status at a glance.

3. As a user, I want to register for tournaments, view results, and share tournament details with others.

**Comment by rqueiroz20** [comment]
The user stories you grouped together for spectators and participants don't really apply to spectators, since I would assume a user becomes a spectator after they join a tournament that is already in progress. We could talk to the team working on User Management to create an attribute related to a user's status as a participant or spectator. If you want to talk about it more, we can. I was thinking of modifying some of these anyway and we could come to a more unified approach.

**Comment by jb-01** [comment]
That sounds good to me. Feel free to close the issue if those user stories are comprehensive enough for what we currently have modeled out.

**Comment by rqueiroz20** [comment]
For now, the user stories we have for displaying tournaments lines up well with those in #33. I'll close this issue for now, but once we speak to the User Management team, we can revisit our approach.

**Comment by MikeChen012345** [comment]
I am thinking about adding this part to the user stories to "general":
- Justin can see the profile of each player in the tournament, including their past winning rate, past strategies (if possible, e.g., in a card game), and opponents, so he can decide what strategy to use later. (This feature is highly dependent on the user profile and matches group)

**Comment by rqueiroz20** [comment]
@MikeChen012345 The user story is a good one and we should take it into account eventually, but I'm more concerned about getting a working prototype done first, then we can add it on at a later date. Perhaps this could be another issue put into the backlog?

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
User stories look good. It doesn't really affect your user stories, but maybe adjust them to single elimination since you guys have decided to go with that route instead of double elimination. I took off points from this issue because there was no closing statement that explained what you guys did. Also, please do not leave unnecessary comments on the issue. If you need to discuss the issue, that should be done on Slack. Instead, the comments are a space for periodic updates on what work has been done.
