### ISSUE TITLE
Allow for searching notifications and filtering by type, sender and sorting by date in inbox

### ISSUE THREAD

**Issue by omarelkashef** [uchicago-cs/chigame#351]
In the inbox page, we need to allow users to search through their notification using words that match the messages body of the notification. They should also be able to filter their inbox according to sender and type as well as sort by date from most to least recent and vice versa

**Comment by 24raniwalar** [comment]
Closing Statement: We are closing this issue even though it only allows for the first half of the title. The PR allows for users to search for notifications using the universal search bar. The results are displayed using search_results.html rather than user_inbox.html and so filtering can be handled in a future issue. Both developers worked on all parts of the issue.

**Comment by elizabethli31** [comment]
Issue Score: Satisfactory

Comments:
Lacking updates for a pretty big PR. Otherwise, great work!
