### ISSUE TITLE
(tournaments) Research possible tournament types to be implemented

### ISSUE THREAD

**Issue by MikeChen012345** [uchicago-cs/chigame#36]

**Comment by MuyanXie** [comment]
We will research what types of tournaments exist and document them. After getting some results (>= 4 may be great), we plan to analyze the most appropriate/easy-to-implement/popular type and implement it first in Sprint 2. If we have more time later, we may also choose to implement some other types of tournaments following the ranking.

**Comment by MikeChen012345** [comment]
The task described in issue #36 can be considered done currently. I (Zihao Chen) have done some research on 4 different kinds of tournaments (round-robin, single-elimination, double-elimination, and multi-stage) and some descriptions of what each of these kinds are. The result is presented in the  [(Wiki)](https://github.com/uchicago-cs/chigame/wiki/Tournaments-~-Potential-Tournament-Types). Based on the document, we should be able to determine the most appropriate form to be implemented. In the next step, we can start choosing the one for implementation.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great work! Glad you guys included multiple different types of tournaments and clear explanations of all four. In the future, for documentation related issues, please link the documentation as part of a comment or in the closing statement. Also, for the summary/goal of the issue, include that in the description of the issue rather than a comment.
