### ISSUE TITLE
(game management) User story for registered users (specific game in mind, generally browsing) (Daniel, Ryan, Owen))

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#43]
## User Stories for Registered Users

**Goal:** To formulate clear and comprehensive user stories that portray how users navigate browsing games and view game detail pages.

**Comment by frowenz** [comment]
User stories up [here](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories#logged-in-users).

**Comment by frowenz** [comment]
We discussed several questions that are still open while writing this.

1. **Viewing Mode on Browsing Page**: Should we offer a gridview, list view, or both?
   - Current Decision: Start with just a gridview.

2. **Filtering and Sorting Mechanics**: What's the best approach?
   - Inspiration: [Letterboxd's system](https://letterboxd.com/films/popular/) with dropdowns for sorting and filtering seems promising.

3. **Criteria for Filtering and Sorting**: What should users be able to filter and sort by?
   - **Filterable** (tentative list):
     - Playtime
     - Number of Players
     - Complexity
     - Genre
     - Age
   - **Sortable** (tentative list):
     - Popularity
     - Game Name
     - Most Favorited

**Comment by majorsylvie** [comment]
Smaller point, for this trio of user stories:

"
Alex has the ability adjust the visibility of his lists. The possible options are Private, Unlisted, or Public.
Alex sends a link to his Games for Parties list to his friend, Emily.
Emily clicks on the link and is able to view the list. She navigates to Alex's page and is able to view all his other public lists.
"

It isn't clear until the end of the last story what alex picked for his visibility. I would add some extra works specifying which of the 3 visibility options Alex picks for his list. 

Since another user story could be him accidentally sending a private link and Emily getting something (a 404, a "you don't have permission" page, a "request the owner for access" page, etc...)

Please add this comment then we can reclose this issue

**Comment by frowenz** [comment]
Thanks for bringing that up. I have updated wording to address the concern:

```
Alex can view his choose to add, remove, or reorder games from his custom lists on his Lists page.
Alex has the ability adjust the visibility of his lists. The possible options are Private, Unlisted, or Public. By default, lists are Public. He sets the visibility of Games for Parties to Unlisted.
Alex sends a link to his Games for Parties list to his friend, Emily.
Emily clicks on the link and is able to view the list. She navigates to Alex's page and is able to view all his public lists.
If Alex had set the visibility to Private, Emily would have gotten a 404 Error when viewing the link
```

Also, I chose to say that list are Public by default. My logic was that this makes the site feel more *social*. This is something worth thinking about further. Perhaps in user settings, there could be an option to default list visibility. I know other sites do this.


## Closing Statement:
We have completed the user stories and added them to the wiki. Each of us worked on writing them collectively in a google document. @danielngira and @rakrusch wrote the first draft. @frowenz  edited this draft and formatted it for the wiki.

**Comment by majorsylvie** [comment]
Issue Score: Satisfactory

Comments:
Good job defining the user stories and adding a good closing comment!
Good work addressing feedback as well as being transparent about what questions you had an how you resolved them, that is incredibly valuable to give in updates and I highly encourage you to continue this.

You did not provide a milestone and this issue lasted two sprints. In the future, particularly prioritize documentation/specification work.
Please add milestones!

Overall, great work, use these user stories well, and keep going!
