### ISSUE TITLE
 Implemented User Retrieval API Endpoint with GET Method at /api/users

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#49]
**Goal**: Developed a robust API endpoint at /api/users to facilitate the retrieval of user usernames. This strategic implementation lays the groundwork for upcoming features, allowing for the display of basic user information. The focus is on scalability, ensuring smooth listing of all user usernames and laying the foundation for an extensive user display system in subsequent updates. This initiative serves as a pivotal step toward enhancing the overall user experience on chigame.

**Comment by cuyakonwu** [comment]
Successfully created serializers for users at api/serializers.py, created user list view and user detail view at api/views.py to set the foundation of gathering data on users on the chigame platform.

**Comment by majorsylvie** [comment]
Issue Score: Needs Improvement

Comments:
Few things:
**Your summary is lacking information.** You mention that the `/api/users/` endpoint will be made. You do not mention what specific endpoints you are planning, nor do you mention what methods they will support, nor any notes about their expected behaviour.

This is particularly important because you made two endpoints! The list AND detail view. So not mentioning the detail view at all in any writing on the issue is too little information.

The text about:
> The focus is on scalability, ensuring smooth listing of all user usernames and laying the foundation for an extensive user display system in subsequent updates. This initiative serves as a pivotal step toward enhancing the overall user experience on chigame.
Could be meaningful if you expanded it all, explained what the impacts of what you were saying is, or gave more details on what this "extensive user display system".

Without any justification these words are adding length but no substance to your summary.

Next, **you did not write any updates to this issue**
especially when the PR had a large amount of changes requested, and there are multiple endpoints created, you had multiple moments where work was progressing which would have merited update comments. 

Then finally, **this issue took two sprints.**

Overall, please focus on writing more descriptive summaries and adding closing comments to you work!
