### ISSUE TITLE
(apis) Create endpoints to fulfill GET requests for individual lobbies at lobbies/request url

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#51]
Goal: Set up an endpoint that retrieves information about ChiGame lobbies from API, serialized in JSON. This will be done at url "chigame/lobbie/request", and can be accessed by ChiGame users as well as third-party websites. The lobbies get request would include how many players, what game is being played (including whether its tournament or match), and availability (private or public lobby, etc.).

**Comment by abrahmasandra** [comment]
The goals of this issue was to create the detail view for the Lobby (i.e. support GET requests to get the information of an individual lobby). The URL endpoint has been changed to `/api/lobbies/<LobbyID>` and this functionality of getting the information for a specific lobby (as specified by the LobbyID) is supported through this endpoint. The progress has been documented in issue #52.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Thank you for linking the other relevant issue.
