### ISSUE TITLE
Create API Endpoint: POST new individual lobbies

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#53]
**Goal**: Post any given lobbies through an api endpoint. To do this we need to create a lobby entity with attributes such as active users and games. We then need to store the data using Django RESTful API.

**Comment by abrahmasandra** [comment]
Closing Comment:

The goals of this issue was to create the POST endpoint for the Lobby (i.e. support the creation of a new lobby through some endpoint and POST data). The URL endpoint has been changed to `/api/lobbies/` and this functionality of creating a lobby can be done by submitting a POST request with the required form data to that endpoint. The progress has been documented in issue https://github.com/uchicago-cs/chigame/issues/52.

**Comment by abrahmasandra** [comment]
Closing Comment:

The goals of this issue was to create the POST endpoint for the Lobby (i.e. support the creation of a new lobby through some endpoint and POST data). The URL endpoint has been changed to `/api/lobbies/` and this functionality of creating a lobby can be done by submitting a POST request with the required form data to that endpoint. The progress has been documented in issue https://github.com/uchicago-cs/chigame/issues/52.

**Comment by majorsylvie** [comment]
This issue's work was fully subsumed by issue #52 thus I am closing this as a duplicate.

**Comment by majorsylvie** [comment]
Issue Score: Ungradable

Comments:
ungradeable since it is a duplicate
