### ISSUE TITLE
Create API Endpoint: GET list of friends given a user (ENDPOINT: `/api/users/<int:pk>/friends`)

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#54]
**Goal**

We want to be able to get a list of friends given the `user_id` or primary key of the user. We should eventually make this list of friends be private if the user doesn't want to share the list of friends with everyone. This is useful so that a User can get their list of friends easily through the API. 

ENDPOINT: `/api/users/<int:user_id>/friends` -- this allows for the endpoint to know the specific user (user_id) to look at the friends for

We will know this issue is finished if we can use a GET request to get a list of the user's friends

**Comment by abrahmasandra** [comment]
In the future, we may be interested in adding support for POST requests in order for a user to make a friend request.

**Comment by abrahmasandra** [comment]
The endpoint we used: `/api/users/<int:user_id>/friends`, because the friends of a given user is stored within the specific user's information. We get the specific users information through the detail view of the user, which is at the `/api/users/<user_id>` as specified by issue #49. To get the friends from this information, we should just nest the detail view URL with "/friends/", to get the specific friends attribute of a specific user.

**Comment by abrahmasandra** [comment]
As of now, it is difficult to use this endpoint, as issue #49 is not completed yet. When Issue #49 is completed, the list and detail API views for the User class will be completed. This will make it possible for someone to create users through the API, as well as access their `user_id`, which can then be used to get their friends through the endpoint created in this issue.

**Comment by abrahmasandra** [comment]
Closing Comment:

Added endpoint `/api/users/<int: user_id>/friends` that supports `GET`  requests. This endpoint returns a list of the users friends given the users `user_id`, which is specified in the `URL` endpoint.

**Comment by majorsylvie** [comment]
Issue Score: Excellent
