### ISSUE TITLE
 POST individual users (esteban conrad)

### ISSUE THREAD

**Issue by cuyakonwu** [uchicago-cs/chigame#56]
**Goal** Create an API endpoint that allows for the creation of new users using a POST request. This would require the user to input their username, email and password. Creating an account would allow the website to store information on the games you play and statistics from said games.

**Comment by majorsylvie** [comment]
Looking back at this, this issue is not complete. 

The process for creating a user under this method only allows you to `POST` a user’s `username` and `email`, but not `password`

<img width="1222" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/82d33fb6-394c-4e0c-9b75-56733968f5ab">

What this endpoint does allow is the creation of a user with a an email that can be used to “reset password”. so any user created via the endpoint will need to go through the resetting password process before being able to sign in.

If your goal for this task is to have a `POST` request lead to the creation of a user which can directly sign into chigame, this is not done.

My apologies, this should've been caught sooner.

**Comment by majorsylvie** [comment]
Also the titling for the associated PR is then wrong, because that is only referencing data retrieval (`GET` detail and list requests) not `POST`ing new data #74

**Comment by majorsylvie** [comment]
#291 Has implemented this functionality.

**Comment by majorsylvie** [comment]
Issue Score: Satisfactory

Comments:
Satisfactory as this lacks a closing comment and spanned 3 sprints.
Thank you for your work
