### ISSUE TITLE
Write user stories for forum admins

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#57]
This issue centers on creating detailed user stories for the admin user role within the board games website forums. We will investigate the unique requirements and challenges faced by admins, from moderating content, managing user roles, addressing reports, to overseeing general forum maintenance. By capturing the multifaceted tasks and responsibilities of an admin, we hope to ensure the platform's back-end capabilities are streamlined, intuitive, and efficient. The goal is to shape a platform where administrative tasks are not just manageable but are also efficient and effective, enhancing the overall health and quality of the forum.

**Comment by Benjoman12** [comment]
I am posting the following user stories on how we can look at possible functionality for Admin users:	

Managing Reports:
    * Sarah logs in and sees a list of forums each with a number contained in a red bubble that shows how many reports have been made on that forum, to quickly identify where her attention is needed.
    * Sarah organizes the forums by most recent report, rate of reports on that forum, and overall quantity of reports on that forum, to prioritize her moderation efforts accordingly.

Thread and Comment Moderation:
    * Sarah clicks on a thread and sees a list of participants and a list of community violations within that thread, to take appropriate moderation actions.
    * Sarah decides to delete a problematic thread, she is prompted with a confirmation before the thread is deleted to ensure accurate moderation.
    * In another instance, Sarah decides to delete a derogatory comment and is prompted with a confirmation before the comment is deleted, to maintain a respectful discussion environment.
   
User Management:
    * Sarah clicks on a user's profile and is taken to a page with two lists: one showing which forums they are on and comments made on those forums, and another listing community guideline violations and details about those violations, for a comprehensive understanding of the user's activity and behavior.
    * Sarah bans a user from a thread due to disrespectful behavior, she is prompted with a confirmation before the ban is enacted to ensure accurate moderation.
    * Sarah bans a user from commenting on the forum due to repeated guideline violations, to uphold the integrity and constructive nature of discussions on the forum.

Notification Management:
    * Sarah receives notifications for new reports, mentions, or other important events within the forum, to respond in a timely manner.

Performance Monitoring:
    * Sarah accesses analytics and performance metrics of the forum, to monitor and improve the forum's health and engagement over time.

**Comment by bburgess19** [comment]
Overall, great thoughts; any user story I don't comment on, I approve :) Will leave my comments below:

### Managing Reports:
>  Sarah organizes the forums by most recent report, rate of reports on that forum, and overall quantity of reports on that forum, to prioritize her moderation efforts accordingly.

Is this a toggle which does all of this sorting as one operation, or is it up to her to apply those filters? Perhaps it could look like:

*Sarah organizes the forums by most recent report. Not satisfied with this, she removes the filter and re-sorts the forums by highest post rate in the last 24 hours. She does a similar process with sorting criteria based on largest total posts on the forum.*

### User Management
> Sarah clicks on a user's profile and is taken to a page with two lists: one showing which forums they are on and comments made on those forums, and another listing community guideline violations and details about those violations, for a comprehensive understanding of the user's activity and behavior.

This is sort of related to the registered user stories, but from the admin point of view, we may only want to consider a user part of a forum if they've commented on it somehow. My thoughts:

*Sarah clicks on a user's profile and is taken to a page with two lists: one showing __all of comments on every forum they've commented on__, and another listing community guideline violations and details about those violations, for a comprehensive understanding of the user's activity and behavior.*

> Sarah bans a user from a thread due to disrespectful behavior, she is prompted with a confirmation before the ban is enacted to ensure accurate moderation.

We could specify she decides to do this after reviewing their account. Also, do we want to delineate between banning a user from a forum vs just a thread?

*__After reviewing a user's account__  Sarah bans a user from a thread due to disrespectful behavior, she is prompted with a confirmation before the ban is enacted to ensure accurate moderation.*

> Sarah bans a user from commenting on the forum due to repeated guideline violations, to uphold the integrity and constructive nature of discussions on the forum.

Can be omitted because the previous story would catch this unless we want to distinguish between bans on a thread vs a forum

### Performance Monitoring
> Sarah accesses analytics and performance metrics of the forum, to monitor and improve the forum's health and engagement over time.

We should specify when she views these analytics:

*__When visiting any forum page__ Sarah sees analytics and performance metrics for that forum, to monitor and improve the forum's health and engagement over time.*

**Comment by Benjoman12** [comment]
Updated Admin User Stories with previous suggestions and comments.

**Managing Reports:**
*Sarah organizes the forums by most recent report. Not satisfied with this, she removes the filter and re-sorts the forums by highest post rate in the last 24 hours. She does a similar process with sorting criteria based on the largest total posts on the forum, to prioritize her moderation efforts accordingly.

**Thread and Comment Moderation:**
*Sarah clicks on a thread and sees a list of participants and a list of community violations within that thread, to take appropriate moderation actions.
* When Sarah decides to delete a problematic thread, she is prompted with a confirmation before the thread is deleted to ensure accurate moderation.
* When Sarah decides to delete a derogatory comment, she is prompted with a confirmation before the comment is deleted, to maintain a respectful discussion environment.

**User Management:**
*Sarah clicks on a user's profile and is taken to a page with two lists: one showing all the comments on every forum they've commented on, and another listing community guideline violations and details about those violations, for a comprehensive understanding of the user's activity and behavior.
*After reviewing a user's account, Sarah bans the user from a thread due to disrespectful behavior, she is prompted with a confirmation before the ban is enacted to ensure accurate moderation.

**Notification Management:**
*Sarah receives notifications for new reports, mentions, or other important events within the forum, to respond in a timely manner.

**Performance Monitoring:**
*When visiting any forum page, Sarah sees analytics and performance metrics for that forum, to monitor and improve the forum's health and engagement over time.

**Comment by Benjoman12** [comment]
Since the suggestions have been implemented and there are no additional comments, I am finalizing these admin user stories for now and adding them to the wiki. If anyone has any additional comments in the future, we can reopen this issue and visit the stories per need basis.

As for task handling, I came up with the user stories, along with adding them into the wiki. Ben Burgess helped edit the user stories after initial creation.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great job! Appreciate you all keeping the back and forth for production and feedback on the issue.

This issue did last 2 sprints, in the future if you have tasks that you carried over from the previous sprint and feel are close to done, do them right after the team meeting.

Overall, great job and keep going!
