### ISSUE TITLE
Write user stories for unregistered forum users

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#58]
This issue focuses on developing user stories for unregistered users on our board games forum. We'll explore passive interactions like browsing and reading, understand access limitations, and identify factors motivating registration. By mapping the unregistered user journey, we aim to enhance the forum's design to encourage registration and active participation.

**Comment by giomhern** [comment]
This issue focuses on developing user stories for unregistered users on our board games forum. We'll explore passive interactions like browsing and reading, understand access limitations, and identify factors motivating registration. By mapping the unregistered user journey, we aim to enhance the forum's design to encourage registration and active participation.

**Comment by giomhern** [comment]
In brainstorming some possible ideas for functionality for unregistered users, I came up with these user stories, albeit some might me repetitive given the restricted functionality for these type of users: 

1. Jamie visits the ChiGame forum and browses top threads. Intrigued by several discussions, they realize they can't join in without an account.
2. Casey stumbles upon a compelling ChiGame forum debate about a trending game. Wanting to reply, they're prompted to log in or register.
3. Jordan, a frequent ChiGame forum reader, bookmarks intriguing threads for future reading, yet is aware they can't directly interact or post replies.
4. Alex discovers the "User Reviews" section on ChiGame. They read multiple reviews, and really like this one particular review. They wish to upvote the comment, but cannot because they are a registered user. 
5. Taylor finds a fascinating game walkthrough thread on ChiGame. They're keen on asking questions but are blocked by the login prompt.
6. Jordan, on another visit, notices a captivating "Game Theories" thread but sees a lock icon, indicating some threads may have restrictions for unregistered users.
7. Casey, eager to share a game tip, starts typing a response in a ChiGame thread but is redirected to the registration page upon hitting "Submit".
8. Jamie wishes to be notified of new replies in a popular ChiGame thread but sees a reminder that thread subscription is only for registered members.
9. Alex, after reading a heated ChiGame debate, wishes to report a possibly rule-breaking comment but can't access the "Report" function without an account.

Feel free to leave any comments on any additional functionality we can include on this!

**Comment by bburgess19** [comment]
Overall, I like these stories. A couple of thoughts:

Stories 1, 2, 5, and 7 describe a similar use case, so it may make sense to consolidate them into one:

"Jaime visits a ChiGame forum and, intrigued by a thread debating a trending game, types a reply out to one of the comments. On submitting, he is redirected to a login page describing comments can only be used for registered user."

Otherwise, these are great stories to me!

**Comment by majorsylvie** [comment]
Design note, you might want to not even let users type replies until they're logged in. 
Since imagine if you see a box, are allowed to type in it, then only upon submitting do they tell you you can't submit (then likely wiping your input).
Instead adding a "please sign in to comment" prompt _in place_ of a comment box would be a "kinder" design (aka have better UX)

**Comment by giomhern** [comment]
I like these suggestions and I think the comment on UX is better! I had preferably put down two just to gather which functionality we _would_ like to incorporate, but I second this!

This is the revised set of user stories:

1. Jaime visits a ChiGame forum and, intrigued by a thread debating a trending game, and intending to reply is met with "Please sign in to comment" prompt to be able to submit a reply. 
2. Jordan, a frequent ChiGame forum reader, bookmarks intriguing threads for future reading, yet is aware they can't directly interact or post replies.
3. Alex discovers the "User Reviews" section on ChiGame. They read multiple reviews, and really like this one particular review. They wish to upvote the comment, but cannot because they are a registered user.
4. Jordan, on another visit, notices a captivating "Game Theories" thread but sees a lock icon, indicating some threads may have restrictions for unregistered users.
5. Jamie wishes to be notified of new replies in a popular ChiGame thread but sees a reminder that thread subscription is only for registered members.
6. Alex, after reading a heated ChiGame debate, wishes to report a possibly rule-breaking comment but can't access the "Report" function without an account.

Closing this issue for now as well!

**Comment by majorsylvie** [comment]
@giomhern @bburgess19 Please take these user stories and publish them as a wiki page! This way we (or anyone else) won't have to find this specific issue to figure out what y'all's user stories are.

**Comment by giomhern** [comment]
The suggestions have been revised and incorporated into the refined user stories by removing redundant stories  and/or better thought processes for these users. The stories have been added to the wiki under the forums user stories, along with the unregistered users. 

As for task handling, I handled the description on this end along with the creation of the user stories. Ben provided ample feedback to remove redundancy in the stories.

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
Great job! I appreciate y'all using the issue tracker to hold conversation about the user stories.
Thank you for actually creating the wiki page. 
In the future, please remember to only close with a comment that describes **why the work was done** and also **what work was done by each developer**.

Great work and keep going!
