### ISSUE TITLE
Document which entities are necessary for forum functionality

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#60]
This issue entails the creation of an Entity Relationship Diagram (ERD) outlining the necessary entities and their relationships for implementing forum functionality on the chigame platform. The ERD should illustrate entities including but limited to users, threads, posts, categories/communities, and any auxiliary entities such as tags or attachments, along with their interrelations. This documentation will aid in structuring development and ensuring a clear understanding of the database schema among the development team.

**Comment by joshuamonroe** [comment]
I've created a Google Doc and begun working on the ERD.

https://docs.google.com/drawings/d/1fhi0fNyc_qiJxcUYkx3oLqL22nnRpJU9Z5Tz1nuV0I4/edit?usp=sharing

**Comment by bburgess19** [comment]
LGTM. I agree completely with this ERD. Feel free to close unless there's some lingering doubts.

**Comment by joshuamonroe** [comment]
I have published v1 of the ERD to the wiki and marking this issue as done.

https://github.com/uchicago-cs/chigame/wiki/Forums-~-Entity-Relationship-Diagram-(ERD)

![Image](https://github.com/uchicago-cs/chigame/assets/59244307/9df6b9c8-23a2-406e-a9b9-0181da38f2e4)

**Comment by majorsylvie** [comment]
Issue Score: Satisfactory



Comments:
Thank you for posting the ERD as a screenshot instead of google docs link.
As discussed in the sprint 2 meeting, in the future avoid the use of external private sources like google docs in the interest of keeping our notes and documentation accessible and associated with the Chigame repo.

Along with that, the title for this issue is somewhat vague, with the description being much clearer in saying "We're making an ERD and figuring this out".

Going forward try to include information about your goals for an issue in its title.

Overall, great work, keep going!
