### ISSUE TITLE
Write user stories for registered forum users

### ISSUE THREAD

**Issue by bburgess19** [uchicago-cs/chigame#62]
This issue focuses on crafting comprehensive user stories for registered users engaging with the forums on our board games website. We will delve into capturing essential aspects of user interaction, including browsing, engagement, moderation, notifications, profile management, and support. Through these user stories, we aim to meticulously understand and delineate the user’s journey, expectations, and potential challenges, ensuring that the forum development resonates with user needs and preferences. The outcome will be insights that will guide and enhance the robust development and optimization of the forum experience, making it more intuitive, engaging, and user-friendly.

**Comment by giomhern** [comment]
As with unregistered users, I am adding here following user stories on how we can look at possible functionality for **registered users**: 

1. Sarah logs in and uses the search bar to find discussions on her favorite board game.
2. Alex creates a new thread, uploading images and writing a review about a game he recently played.
3. Jamie receives notifications when other users reply to a thread she's active in or mention her username.
4. Chris bookmarks threads for easy access and organizes them by game genre.
5. Jordan upvotes a helpful post, appreciating the user's contribution to a discussion.
6. Taylor reports a comment that violates the forum's guidelines.
7. Sarah edits her comment in a thread to correct a game rule she previously mis-stated.
8. Alex deletes one of his older comments that he no longer feels is relevant.
9. Jamie subscribes to a thread to receive email updates on new replies.
10. Jordan views the forum's leaderboard, checks top contributors, and aims to increase his participation.

Again, let me know of any possible suggestions to make to this and we can certainly modify!

**Comment by giomhern** [comment]
Since there are no additional comments, I am finalizing these user stories for now and adding them to the wiki. If anyone has any additional comments in the future, we can reopen this issue and visit the stories per need basis. 

As for task handling, I came up with the user stories, along with adding them into the wiki. Ben and Ben both edited and came up with the description of the task.

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
These are straightforward, functional user stories.
Thank you for adding the closing statement about work distribution! 
For future reference if anything is made because of an issue (documentation, pull request, a demo), it is good to include a link to it or at least instruction on where to find it.

So here, you reference making a wiki page, it would be good for you to link said wiki page to this issue.

Overall, good work, keep going!
