### ISSUE TITLE
(matches) create a view for lobby details

### ISSUE THREAD

**Issue by agustinmoses** [uchicago-cs/chigame#66]
Goal: Create a view page for users to be able to view lobby details based on the view to join a lobby.

**Comment by agustinmoses** [comment]
Update: Created an HTML page that displays lobby details.

**Comment by agustinmoses** [comment]
Created path to urls.py and created a corresponding function in views.py

**Comment by xylucien** [comment]
closing statement: task done. Moses and I worked on separate branches for this pull request, and I personally felt like it did not necessarily make things easier than working on one branch together because of having to merge from each other's branch constantly. Perhaps next time we will share one same branch when working towards different issues under the same PR?

**Comment by elizabethli31** [comment]
Issue Score: Excellent!

Comments:
Great job on this issue and first PR! Next time, try to complete issues within one sprint.
