### ISSUE TITLE
Tournament ERD

### ISSUE THREAD

**Issue by jb-01** [uchicago-cs/chigame#84]
## Single-Elimination Tournament ERD Implementation

**Issue Number**: #84

**Description**:
Implement an ERD for single-elimination tournaments:
- Competitors play head-to-head matchups.
- Winners advance, losers are out.
- Can accommodate both single-game and series-based matchups.
- Tip: this structure is similar to NCAA's March Madness with 64 teams.

**Goal**:
Add a robust ERD to our Wiki to efficiently manage and track this tournament structure. Add a new Wiki page to display the ERD.

**Comment by jb-01** [comment]
Please see our new Wiki [page](https://github.com/uchicago-cs/chigame/wiki/Tournament-~-Entity-Relationship-Diagram) with a basic ERD to represent our single-elimination style tournament.

**Comment by rqueiroz20** [comment]
We have a rough draft for the tournament ERD on the Wiki page, but we have not conferred with the Users or Matches groups to determine if our proposed ERD lines up with their models. I have messaged both teams and am currently waiting for their feedback.

**Comment by rqueiroz20** [comment]
I have spoken with both Matches and Users, and for now our groups agree on the path forward regarding our Tournaments ERD. Here is a summary of what everyone did in this issue:

- We all met in person to create the initial Tournament ERD based on the User stories that were listed on the Github Wiki. This is when we decided that a single-elimination tournament type would be the simplest in terms of implementation on ChiGame.
- From there, the three of us typed out our ERD onto [this Wiki page](https://github.com/uchicago-cs/chigame/wiki/Tournament-~-Entity-Relationship-Diagram). I (Rafael Queiroz) sent out messages to the Users and Matches team on Slack to verify that our ERDs lined up with their respective models.
- Once I received their feedback, I told Riyush, who modified the ERD so that it would fit in with the models.
- Joshua reviewed the modified one and saw that everything looked good, and our single-elimination tournament ERD was complete.

I'm going to close the issue here, but if somehow there is something in our ERD we may have to change in the future, we can always revisit our ERD and modify it accordingly. For now though, it suits our purposes.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Nice ERD that creates the tournaments feature!
