### ISSUE TITLE
Design models for single-elimination tournament 

### ISSUE THREAD

**Issue by MuyanXie** [uchicago-cs/chigame#85]
## Description

We are going to try convert the ERD table into the Django models to utilize the ORM and map our entities in the database; we are going to implement the ERD in the models.py file for the tournaments App.

## Goal

Have a viable and reliable models.py file that successfully maps the ERD and serve the relationships between the entities correctly

**Comment by MikeChen012345** [comment]
A models.py has been added to the directory chigame\src\chigame\tournaments. In the file, I have implemented the Tournament, Notification, Chat, and Message models based on the tournaments/ERD.md in the wiki. A pull request #136 has been created corresponding to the changes.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great work on this very large and important issue! You guys did a great job translating the ERD to a model. I'm grading this now because the PR is mostly ready, but make sure to fix the bugs I commented on for the PR. Also make sure to include exactly what each member of the issue did in your closing statement.
