### ISSUE TITLE
Write up user stories for game searching

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#90]
We will write user stories for our search bar features in order to flesh out the exact functionality of our search bar. This will answer questions such as: what do we have the search bar actually search? genre, name, rules, etc..? will we have a search page or just a search bar?

**Comment by willcravitz** [comment]
I reviewed some sites that @frowenz called out for inspiration on how they use search:

- [Letterboxd](https://letterboxd.com/)
- [Rate Your Music](https://rateyourmusic.com)
- [Board Game Arena](https://en.boardgamearena.com/)
- [Goodreads](https://www.goodreads.com/)

Of these I liked the way that BGA and Goodreads handle search best.

1. [Board Game Arena](https://en.boardgamearena.com/)
Search bar lives in the navbar. When you click in the search field, a dark overlay appears over the current page. On this dark overlay is a grid of games. Before you have started typing it lists suggested games and gives an option to pick a random game. As you type it narrows down the grid to a set of games based on the text you've entered. If you press the "enter" key then it takes you to the page of the first game in the grid. You also have the ability to click on any other game in the grid to go to its page. You are never taken to a search results page.

2. [Goodreads](https://www.goodreads.com/)
Search bar lives in the navbar. When you start typing in the search fields, a dropdown appears with books (*only books) that best match the text you've entered. Books listed in the dropdown link to the individual book page. If you enter the search or click "view all results" then you're taken to a search results page. The search results page has tabs for books as well as groups, quotes, other users, and lists. It presents the results within each of these tabs in a list view.

**Comment by willcravitz** [comment]
Based on issue #91, we decided in team meeting that it makes more sense to go for the Goodreads style search.

**Comment by willcravitz** [comment]
Per issue #89, we also want the Rate Your Music type functionality of choosing whether to search for games or users within the searchbar itself.

**Comment by willcravitz** [comment]
@rakrusch, let me know if you have any feedback before we add it to the wiki:

### Searching Games and Users
- Jeff came to the site hoping to play Catan. 
- He clicks on the searchbar in the navbar. The _Games_ category is underlined by default and _Users_ is not. He starts typing "c",..."ca",..."cat",... until a dropdown list of games whose title contains "cat" appears, sorted by relevance.
- Catan is the first title listed in the dropdown. He clicks on the listing and it takes him to the Catan page, where he can view details about the game and start a match.
- Jenny is curious about what strategy games are available to play on the site. 
- She types "strategy" into the searchbar and clicks enter. 
- She is redirected to a search results page. It displays a list of games, some of category strategy, some with "strategy" in their title, sorted by relevance. 
- Jenny clicks on Risk and is taken to the Risk page.
- Jeff is talking to a classmate who mentions they have an account on Chigame with the username "number1_chigamer". 
- He goes the searchbar and clicks on _Users_, which now becomes underlined instead of _Games_. 
- He types in the username "number1_chigamer", and a dropdown list of users appears. 
- Jeff clicks on the little search icon next to the searchbar and is taken to a list of users, sorted by similarity to the search query.
- "number1_chigamer" is the first user listed. Jeff clicks on the account and is taken to his classmate's user page.

**Comment by willcravitz** [comment]
Closing comment: User stories for searching have been written and added to the wiki [here](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories#searching-games-and-users). 

Developer contributions
@willcravitz wrote the initial draft of the user stories, @rakrusch reviewed and gave feedback.

**Comment by rakrusch** [comment]
@willcravitz This all looks really good to me. Just a couple things I might add. Let me know what you think of these.

- Still clicked on _Users_, Jeff misspells the username of another friend who is registered on chigame, typing 'numxbr2_chigamr' in the searchbar
- Jeff sees an empty dropdown list appear, as there are no users on chigame with this username.
- Jeff clicks the small search icon next to the searchbar and is taken to a list of users that is populated with users that have similar usernames to the spelling of the username that Jeff entered into the searchbar.
- Bob especially likes games created by a particular user on chigame and wants to find more games created by that user.
- Bob types that user's username into the search bar (while using the _Games_ category in the searchbar) and clicks the small search icon next to searchbar. Bob now sees a list of games that were created by this user.

**Comment by willcravitz** [comment]
Closing comment: User stories for searching have been written and added to the wiki [here](https://github.com/uchicago-cs/chigame/wiki/Games-~-User-Stories#searching-games-and-users). 

Developer contributions
@willcravitz wrote the initial draft of the user stories, @rakrusch reviewed and provided several additions.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work y'all!

Appreciate the creation of and linking to the wiki page. 

These user stories capture a pretty good scope of use, the only one that stands out is `games made by X user` since we are far off from actually having implemented games, so I'm not personally sure if/when there will be users associated with games.

Keep moving forward!
