### ISSUE TITLE
(game management) Research how to make search bars (ryan, patrick)

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#91]
For this task, we will research existing functionality for making search bars in Django in order to determine how we will go about implementing the search bar.

**Comment by ptlin25** [comment]
The website GeeksForGeeks has a good [example ](https://www.geeksforgeeks.org/implement-search-autocomplete-for-input-fields-in-django/) of a search bar that autocompletes using jQuery UI (a jQuery library, see documentation [here](https://jqueryui.com/autocomplete/)) This could be useful for implementing autocompletion in the search bar

**Comment by ptlin25** [comment]
From many examples such as this [tutorial](https://learndjango.com/tutorials/django-search-tutorial), the basic idea of search bar can be broken down into the following components: 
1. Create a separate search results view, template, and url
2. Add a form with a text input field to the template that sends a GET request to the view
3. In views.py, get the query from the GET request and override the default get_queryset() method provided by ListView

**Comment by ptlin25** [comment]
The HTML form tag with an text input field can be used to make a basic search bar. The action attribute should be set to the url of the search results page.

**Comment by ptlin25** [comment]
In summary, a basic search bar can be implemented using the HTML form tag (including the action and method attributes) and created a new view for the search results based on the query. There are many tutorials such as this [one ](https://learndjango.com/tutorials/django-search-tutorial)about creating a basic search bar and search results page. We can add autocomplete functionality after we complete a basic search bar using the jQuery UI autocomplete widget (see [documentation](https://jqueryui.com/autocomplete/)). Preliminary research into functionality for making a search bar is done, so this issue is complete.
Distribution of work: 
Ryan: research
Patrick: research and documentation

**Comment by majorsylvie** [comment]
Issue Score: Excellent


Comments:
Great job providing frequent smaller updates as y'all went through the task!
For future reference, **please update the title of any issue you work on to _not_ be the title assigned in team meeting**.

This is because the task titles are informal and meant to capture enough such that you can look at them and remember what we talked about.
They are usually not formatted nicely (including extra parentheticals or questions).

Overall, y'all are doing good work, keep going!
