### ISSUE TITLE
Create a basic search that returns search results for games

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#93]
We will create an initial search bar that returns results without any autocompletion or suggestions. We will implement a basic search bar that has a dropdown menu that can be used to specify whether the query is for games or users. This search bar will be placed in the navigation bar.

**Comment by ptlin25** [comment]
Created new branch `game-management/basic-search-bar` for this issue

**Comment by ptlin25** [comment]
Added html code for search bar

**Comment by ptlin25** [comment]
Search bar has been created. There is a dropdown menu next to the search bar to specify whether the user is querying users, games, etc. The dropdown menu dynamically changes the action attribute of the search bar. In other words, when the user switches the selected option in the dropdown menu, the search will link to different pages.

**Comment by ptlin25** [comment]
I was thinking about implementing full text search, but it requires using PostgreSQL while ChiGame is currently using SQLite. if we switch to PostgreSQL in the future, we can think about using PostgreSQL's more advanced querying options

**Comment by ptlin25** [comment]
The basic search bar has been complete and added to the navigation bar. The search bar includes a dropdown menu to specify if the search is for games, users, etc. This issue will now be closed and completed via pull request #176. The next steps include adding autocompleting for game names (#95) and adding support for searching for games by the producer, artist, or designer (#170).

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
@ptlin25 In the future, if you're editing someone elses comment significantly (like the summary here), please mark that you edited the comment with your name, since it's not obvious that _someone else_ edited the comment when all it says is `(edited)`.

For the task, great work! I particularly appreciate you mentioning the desired expansion to PostgreSQL as well as linking relevant future issues and related PR's.

Makes this issue well-documented and easy to understand.

Keep going!
