### ISSUE TITLE
Update game list view to be a grid of game covers/posters

### ISSUE THREAD

**Issue by rakrusch** [uchicago-cs/chigame#96]
We will work on making a game list view for the games in the Chigame database. The listview will include the name of the game and a cover photo.

**Comment by frowenz** [comment]
This issue requires we first complete the game model, #92. It would also benefit from having fixtures, #98.

Regardless, I was able to make a protoype using only a list of images. See below:

https://github.com/uchicago-cs/chigame/assets/69015620/1a9a01c2-2a76-4fd7-b572-fc81837f7c39

Features added:
- view and url routing
- css grid
- game item expands on hover

Features missing:
- linking to detail pages
- displaying name and images actually associated with things in our database

We should also find a good Image Not Found image.

**Comment by frowenz** [comment]
Also, it is worth thinking about where to store images. For the time being we can just link to BGG images but I imagine we eventually want the capacity to have ChiGame specific images stored somewhere. I am not sure what the best way of doing this is. Perhaps this could be its own issue.

**Comment by willcravitz** [comment]
Was looking into Bootstrap for a different issue (since bootstrap is already loaded into the base template) and thought [Bootstrap cards](https://getbootstrap.com/docs/5.3/components/card/) could be helpful for this. Specifically check out [this section](https://getbootstrap.com/docs/5.3/components/card/#grid-cards) on grid cards.

**Comment by willcravitz** [comment]
Brought `game-management/browse` branch back up to date with dev. I deleted the placeholder image data in the `browse_view` view since I felt that this should be covered by the fixtures from issue #98.

I left `game_browse.html` and `game_list.html` alone and wrote a new `game_grid.html` using Bootstrap cards. Leaving it as an open question what we should keep and delete for the future. This is what it looks like:


![Image](https://github.com/uchicago-cs/chigame/assets/93291811/cca3f024-4f81-45da-b07f-38c5083b3e91)

A few other considerations:
1. Should we have match create and join buttons on the cards?
2. Should we have a more details link, or hover and click on the card to get the game detail, or neither?

**Comment by frowenz** [comment]
> 1. Should we have match create and join buttons on the cards?

For now, it might be best to just have a PLAY button on the games detail page that ships off the user to matches and tournament land (given that we are not exactly sure how those teams want to handle this).

> 2. Should we have a more details link, or hover and click on the card to get the game detail, or neither?

Hover and click to go the page would be by vote.

**Comment by frowenz** [comment]
Nice UI btw!

**Comment by frowenz** [comment]
Closing comment of associated PRs:

> We developed a page featuring a grid layout to showcase games.
> 
> This involved crafting a template page enhanced with nice CSS. Both @frowenz and @willcravitz worked on this page. My contribution was the initial creation of the basic grid layout, while @willcravitz enhanced it by integrating bootstrap cards for a more visually appealing. I made some final adjustments to these cards, such as better responsiveness and consistent positioning of the titles.
> 
> Looking ahead, there are a couple of areas for improvement:
> 
> The descriptions currently have no length limit, which needs to be addressed.
> The page's mobile responsiveness is currently suboptimal and requires enhancement.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Wonderful work y'all!
@frowenz awesome updates, appreciate you including video evidence of your work, as well as working on prototypes first. 
@willcravitz thank you for your styling work and seeing how bootstrap would work with this.
Together y'all have made a truly wonderful feature and done so while being very transparent and meaningfully verbose in tracking your work.

This is exactly what I'd want a great issue to look like.

Thank you both for your work.
